SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS board;
SET FOREIGN_KEY_CHECKS=1;
CREATE TABLE IF NOT EXISTS board
(
    id              INTEGER         NOT NULL    AUTO_INCREMENT      PRIMARY KEY,
    title           VARCHAR(20)     NOT NULL    UNIQUE KEY,
    created_at      TIMESTAMP       NOT NULL    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);