DROP TABLE IF EXISTS `board`;

CREATE TABLE `board` (
	`id`	        INTEGER	        NOT NULL    AUTO_INCREMENT      PRIMARY KEY,
	`title`	        VARCHAR(10)	    NOT NULL,
	`created_at`	TIMESTAMP	    NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	    NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);