DROP TABLE IF EXISTS `bookmark`;

CREATE TABLE `bookmark` (
	`id`	        INTEGER	        NOT NULL	AUTO_INCREMENT      PRIMARY KEY,
	`user_id`	    VARCHAR(20)	    NOT NULL,
	`post_id`	    INTEGER	        NOT NULL,
	`created_at`	TIMESTAMP	    NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	    NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);