DROP TABLE IF EXISTS `comment_like`;

CREATE TABLE `comment_like` (
	`id`	        INTEGER	        NOT NULL	AUTO_INCREMENT      PRIMARY KEY,
	`created_at`	TIMESTAMP	    NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	    NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`user_id`   	VARCHAR(20)	    NOT NULL,
	`comment_id`	INTEGER	NOT     NULL
);