DROP TABLE IF EXISTS `post_like`;

CREATE TABLE `post_like` (
	`id`	        INTEGER	    NOT NULL	AUTO_INCREMENT      PRIMARY KEY,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`user_id`	    VARCHAR(20)	NOT NULL,
	`post_id`	    INTEGER	    NOT NULL
);