DROP TABLE IF EXISTS `post_image`;

CREATE TABLE `post_image` (
	`id`	        INTEGER	        NOT NULL    AUTO_INCREMENT      PRIMARY KEY,
	`img_path`	    VARCHAR(200)	NOT NULL,
	`created_at`	TIMESTAMP	    NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	    NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`post_id`	    INTEGER	        NOT NULL
);