DROP TABLE IF EXISTS youtube;
CREATE TABLE `youtube` (
	`id`	        INTEGER	        NOT NULL    AUTO_INCREMENT      PRIMARY KEY,
    `thumb_nail`    VARCHAR(250)    NOT NULL    UNIQUE KEY,
    `title`         VARCHAR(100)    NOT NULL,
    `link`          VARCHAR(250)    NOT NULL    UNIQUE KEY,
	`created_at`	TIMESTAMP	    NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	    NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;