name: SEGORANG Development Deployment

on:
  push:
    branches:
      - develop

env:
  AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
  AWS_S3_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION}}
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_PW: ${{ secrets.DOCKERHUB_PW }}
  SEGORANG_DEV_HOST: ${{ secrets.SEGORANG_DEV_HOST }}
  SEGORANG_DEV_PORT: ${{ secrets.SEGORANG_DEV_PORT }}
  SEGORANG_DEV_USER: ${{ secrets.SEGORANG_DEV_USER }}
  SEGORANG_DEV_PW: ${{ secrets.SEGORANG_DEV_PW }}
  SEGORANG_DEV_ENV_PATH: ${{ secrets.SEGORANG_DEV_ENV_PATH }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy: 
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USER }}
        password: ${{ env.DOCKERHUB_PW }}

    - name: Download env file from S3
      uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        aws_access_key_id: ${{ env.AWS_S3_ACCESS_KEY }}
        aws_secret_access_key: ${{ env.AWS_S3_SECRET_KEY }}
        aws_region: ${{ env.AWS_REGION }}
        source: ${{ env.SEGORANG_DEV_ENV_PATH }}
        destination: './segorang-server/.env'

    - name: build and release to DockerHub
      env:
        NAME: ${{ env.DOCKERHUB_USER }}
        REPO: segorang-server
      run: |
        cd ./segorang-server
        docker build -t $REPO .
        docker tag $REPO:latest $NAME/$REPO:latest
        docker push $NAME/$REPO:latest